export type LangCode = "en" | "es" | "pt" | "fr" | "de" | "it" | "ht";

export const translations: Record<string, Record<LangCode, string>> = {

  /* ── HEADER / NAV ── */
  "nav.services":     { en: "Services",     es: "Servicios",      pt: "Serviços",       fr: "Services",       de: "Dienstleistungen", it: "Servizi",       ht: "Sèvis" },
  "nav.ourwork":      { en: "Our Work",     es: "Nuestro Trabajo", pt: "Nosso Trabalho", fr: "Nos Travaux",    de: "Unsere Arbeit",    it: "Il Nostro Lavoro", ht: "Travay Nou" },
  "nav.howitworks":   { en: "How It Works", es: "Cómo Funciona",  pt: "Como Funciona",  fr: "Comment Ça Marche", de: "Wie Es Funktioniert", it: "Come Funziona", ht: "Kijan Sa Travay" },
  "nav.whyus":        { en: "Why Us",       es: "Por Qué Nosotros", pt: "Por Que Nós",  fr: "Pourquoi Nous",  de: "Warum Wir",        it: "Perché Noi",    ht: "Poukisa Nou" },
  "nav.areas":        { en: "Areas",        es: "Áreas",           pt: "Áreas",          fr: "Zones",          de: "Gebiete",          it: "Zone",          ht: "Zòn" },
  "nav.faq":          { en: "FAQ",          es: "FAQ",             pt: "FAQ",            fr: "FAQ",            de: "FAQ",              it: "FAQ",           ht: "FAQ" },
  "nav.callus":       { en: "Call Us",      es: "Llámanos",        pt: "Ligue-nos",      fr: "Appelez-nous",   de: "Ruf uns an",       it: "Chiamaci",      ht: "Rele Nou" },
  "nav.textus":       { en: "Text Us",      es: "Escríbenos",      pt: "Mensagem",       fr: "Écrivez-nous",   de: "Schreib uns",      it: "Scrivici",      ht: "Ekri Nou" },
  "nav.contact":      { en: "Contact",      es: "Contacto",        pt: "Contato",        fr: "Contact",        de: "Kontakt",          it: "Contatto",      ht: "Kontakt" },
  "nav.serviceareas": { en: "Service Areas", es: "Áreas de Servicio", pt: "Áreas de Serviço", fr: "Zones de Service", de: "Servicegebiete", it: "Zone di Servizio", ht: "Zòn Sèvis" },

  /* ── HERO ── */
  "hero.title":       { en: "Palm Beach's #1 Junk Removal Service", es: "El Servicio #1 de Remoción de Basura en Palm Beach", pt: "O Serviço #1 de Remoção de Lixo em Palm Beach", fr: "Le service #1 d'enlèvement d'encombrants à Palm Beach", de: "Palm Beachs #1 Schrottentsorgungsservice", it: "Il Servizio #1 di Rimozione Rifiuti a Palm Beach", ht: "Sèvis #1 Retire Fatra nan Palm Beach" },
  "hero.desc":        { en: "Junk removal, sod installation and same-day delivery & pickup. Free estimates, eco-friendly disposal — up to 60% recycled or donated.", es: "Remoción de basura, instalación de césped y entrega/recogida el mismo día. Presupuestos gratis, disposición ecológica — hasta 60% reciclado o donado.", pt: "Remoção de lixo, instalação de grama e entrega/coleta no mesmo dia. Orçamentos grátis, descarte ecológico — até 60% reciclado ou doado.", fr: "Enlèvement d'encombrants, pose de gazon et livraison/collecte le jour même. Devis gratuits, élimination écologique — jusqu'à 60% recyclé ou donné.", de: "Schrottentsorgung, Rasenverlegung und Same-Day-Lieferung & -Abholung. Kostenlose Kostenvoranschläge, umweltfreundliche Entsorgung — bis zu 60% recycelt oder gespendet.", it: "Rimozione rifiuti, posa del prato e consegna/ritiro in giornata. Preventivi gratuiti, smaltimento ecologico — fino al 60% riciclato o donato.", ht: "Retire fatra, enstalasyon gazon ak livrezon/koleksyon menm jou a. Estimasyon gratis, dispozisyon ekolojik — jiska 60% resikle oswa bay." },
  "hero.stat1.n":     { en: "Same Day",  es: "Mismo Día",   pt: "Mesmo Dia",   fr: "Même Jour",   de: "Gleicher Tag",  it: "Stesso Giorno", ht: "Menm Jou" },
  "hero.stat1.l":     { en: "Appointments", es: "Citas",    pt: "Agendamentos", fr: "Rendez-vous", de: "Termine",       it: "Appuntamenti",  ht: "Randevou" },
  "hero.stat2.l":     { en: "Recycled / Donated", es: "Reciclado / Donado", pt: "Reciclado / Doado", fr: "Recyclé / Donné", de: "Recycelt / Gespendet", it: "Riciclato / Donato", ht: "Resikle / Bay" },
  "hero.stat3.n":     { en: "Free",      es: "Gratis",      pt: "Grátis",       fr: "Gratuit",     de: "Kostenlos",     it: "Gratuito",      ht: "Gratis" },
  "hero.stat3.l":     { en: "Estimates", es: "Presupuestos", pt: "Orçamentos",  fr: "Devis",       de: "Kostenvoranschläge", it: "Preventivi", ht: "Estimasyon" },
  "hero.chip1":       { en: "Junk Removal", es: "Remoción de Basura", pt: "Remoção de Lixo", fr: "Enlèvement", de: "Schrottentsorgung", it: "Rimozione Rifiuti", ht: "Retire Fatra" },
  "hero.chip2":       { en: "Sod Installation", es: "Instalación de Césped", pt: "Instalação de Grama", fr: "Pose de Gazon", de: "Rasenverlegung", it: "Posa del Prato", ht: "Enstalasyon Gazon" },
  "hero.chip3":       { en: "Fast Delivery", es: "Entrega Rápida", pt: "Entrega Rápida", fr: "Livraison Rapide", de: "Schnelle Lieferung", it: "Consegna Rapida", ht: "Livrezon Rapid" },
  "hero.chip4":       { en: "Same-day pickup", es: "Recogida el mismo día", pt: "Coleta no mesmo dia", fr: "Collecte le jour même", de: "Same-Day-Abholung", it: "Ritiro in giornata", ht: "Koleksyon menm jou" },

  /* ── SERVICES ── */
  "services.eyebrow": { en: "What We Do",  es: "Lo Que Hacemos", pt: "O Que Fazemos", fr: "Ce Que Nous Faisons", de: "Was Wir Tun", it: "Cosa Facciamo", ht: "Sa Nou Fè" },
  "services.title":   { en: "Four Services.\nOne Reliable Crew.", es: "Cuatro Servicios.\nUn Equipo Confiable.", pt: "Quatro Serviços.\nUma Equipe Confiável.", fr: "Quatre Services.\nUne Équipe Fiable.", de: "Vier Dienstleistungen.\nEin zuverlässiges Team.", it: "Quattro Servizi.\nUna Squadra Affidabile.", ht: "Kat Sèvis.\nYon Ekip Fyab." },
  "services.lead":    { en: "From hauling junk to laying fresh sod and same-day deliveries — we've got Palm Beach County covered.", es: "Desde recoger basura hasta instalar césped fresco y entregas el mismo día — cubrimos todo Palm Beach County.", pt: "De recolher lixo a instalar grama fresca e entregas no mesmo dia — cobrimos todo o Condado de Palm Beach.", fr: "Du ramassage d'encombrants à la pose de gazon frais et aux livraisons le jour même — nous couvrons tout le comté de Palm Beach.", de: "Von der Schrottabholung bis zur Rasenverlegung und Lieferungen am selben Tag — wir haben Palm Beach County abgedeckt.", it: "Dal trasporto di rifiuti alla posa di prato fresco e consegne in giornata — copriamo tutto Palm Beach County.", ht: "Depi ranmase fatra rive instalasyon gazon ak livrezon menm jou a — nou kouvri tout Palm Beach County." },
  "services.cta":     { en: "Request Service", es: "Solicitar Servicio", pt: "Solicitar Serviço", fr: "Demander un Service", de: "Service anfragen", it: "Richiedi Servizio", ht: "Mande Sèvis" },

  /* ── HOW IT WORKS ── */
  "how.eyebrow":      { en: "Simple Process", es: "Proceso Simple", pt: "Processo Simples", fr: "Processus Simple", de: "Einfacher Prozess", it: "Processo Semplice", ht: "Pwosesis Senp" },
  "how.title":        { en: "How It Works",   es: "Cómo Funciona",  pt: "Como Funciona",   fr: "Comment Ça Marche", de: "Wie Es Funktioniert", it: "Come Funziona", ht: "Kijan Sa Travay" },
  "how.lead":         { en: "Getting rid of junk has never been easier. Three steps and it's done — 90% of the time we can take your junk the same day you call.", es: "Deshacerse de la basura nunca ha sido tan fácil. Tres pasos y listo — el 90% de las veces podemos recoger tu basura el mismo día que llamas.", pt: "Livrar-se do lixo nunca foi tão fácil. Três passos e pronto — 90% das vezes podemos recolher o seu lixo no mesmo dia em que liga.", fr: "Se débarrasser des encombrants n'a jamais été aussi facile. Trois étapes et c'est fait — 90% du temps, nous pouvons enlever vos encombrants le jour même.", de: "Den Schrott loszuwerden war noch nie so einfach. Drei Schritte und fertig — 90% der Zeit können wir Ihren Schrott am selben Tag abholen.", it: "Sbarazzarsi dei rifiuti non è mai stato così facile. Tre passaggi e il gioco è fatto — nel 90% dei casi possiamo ritirare i tuoi rifiuti lo stesso giorno.", ht: "Debarase ak fatra pa t janm pi fasil. Twa etap epi fini — 90% tan nou ka pran fatra ou menm jou ou rele." },
  "how.step1.title":  { en: "Call or Text Us", es: "Llámanos o Escríbenos", pt: "Ligue ou Escreva", fr: "Appelez ou Écrivez", de: "Rufen Sie an oder Schreiben Sie", it: "Chiama o Scrivi", ht: "Rele oswa Ekri Nou" },
  "how.step1.desc":   { en: "Give us a call or send a text. Choose a 2-hour arrival window that works for your schedule.", es: "Llámanos o envía un mensaje. Elige una ventana de llegada de 2 horas que funcione para tu horario.", pt: "Ligue ou envie uma mensagem. Escolha uma janela de chegada de 2 horas que funcione para você.", fr: "Appelez-nous ou envoyez un SMS. Choisissez une fenêtre d'arrivée de 2 heures.", de: "Rufen Sie an oder schreiben Sie uns. Wählen Sie ein 2-Stunden-Ankunftsfenster.", it: "Chiamaci o mandaci un messaggio. Scegli una finestra di arrivo di 2 ore.", ht: "Rele nou oswa voye mesaj. Chwazi yon fenèt 2 èdtan pou ariv nou." },
  "how.step2.title":  { en: "We Call 15 Min Ahead", es: "Llamamos 15 Min Antes", pt: "Ligamos 15 Min Antes", fr: "Nous appelons 15 min avant", de: "Wir rufen 15 Min vorher an", it: "Chiamiamo 15 Min Prima", ht: "Nou Rele 15 Min Anvan" },
  "how.step2.desc":   { en: "Our crew calls before arrival so you're never waiting around. We show up on time, every time.", es: "Nuestro equipo llama antes de llegar para que nunca estés esperando. Llegamos a tiempo, siempre.", pt: "Nossa equipe liga antes de chegar para que você nunca fique esperando. Chegamos na hora, sempre.", fr: "Notre équipe appelle avant d'arriver pour que vous n'attendiez jamais. Nous arrivons à l'heure, à chaque fois.", de: "Unser Team ruft vor der Ankunft an, damit Sie nie warten müssen. Wir kommen pünktlich, jedes Mal.", it: "La nostra squadra chiama prima di arrivare così non aspetti mai. Arriviamo in orario, sempre.", ht: "Ekip nou rele anvan rive pou ou pa janm ap tann. Nou rive alè, chak fwa." },
  "how.step3.title":  { en: "Approve Price. We Haul.", es: "Aprueba el Precio. Retiramos.", pt: "Aprove o Preço. Retiramos.", fr: "Approuvez le prix. On enlève.", de: "Preis genehmigen. Wir holen ab.", it: "Approva il Prezzo. Portiamo via.", ht: "Apwouve Pri a. Nou Ranmase." },
  "how.step3.desc":   { en: "Review the upfront quote — no surprise fees. Approve it and we remove your junk on the spot.", es: "Revisa el presupuesto anticipado — sin cargos sorpresa. Apruébalo y retiramos tu basura en el acto.", pt: "Revise o orçamento antecipado — sem taxas surpresa. Aprove e retiramos o seu lixo na hora.", fr: "Examinez le devis — sans frais surprises. Approuvez-le et nous enlevons vos encombrants sur place.", de: "Überprüfen Sie das Angebot — keine Überraschungsgebühren. Genehmigen Sie es und wir holen Ihren Schrott sofort ab.", it: "Esamina il preventivo — senza costi a sorpresa. Approvalo e rimuoviamo i tuoi rifiuti sul posto.", ht: "Revize devis la — san frè sipriz. Apwouve li epi nou retire fatra ou la menm." },
  "how.sameday":      { en: "Same-day service available. 90% of the time we can take your junk immediately after you call.", es: "Servicio el mismo día disponible. El 90% de las veces podemos recoger tu basura inmediatamente después de que llames.", pt: "Serviço no mesmo dia disponível. 90% das vezes podemos recolher o seu lixo imediatamente após ligar.", fr: "Service le jour même disponible. 90% du temps, nous pouvons enlever vos encombrants immédiatement après votre appel.", de: "Same-Day-Service verfügbar. 90% der Zeit können wir Ihren Schrott sofort nach Ihrem Anruf abholen.", it: "Servizio in giornata disponibile. Nel 90% dei casi possiamo ritirare i tuoi rifiuti subito dopo la chiamata.", ht: "Sèvis menm jou disponib. 90% tan nou ka pran fatra ou imedyatman apre ou rele." },
  "how.callus":       { en: "Call Us",  es: "Llámanos",    pt: "Ligue-nos",   fr: "Appelez-nous",  de: "Ruf uns an",   it: "Chiamaci",   ht: "Rele Nou" },
  "how.textus":       { en: "Text Us",  es: "Escríbenos",  pt: "Mensagem",    fr: "Écrivez-nous",  de: "Schreib uns",  it: "Scrivici",   ht: "Ekri Nou" },

  /* ── WHY US ── */
  "whyus.eyebrow":    { en: "Why Choose Us", es: "Por Qué Elegirnos", pt: "Por Que Nos Escolher", fr: "Pourquoi Nous Choisir", de: "Warum Uns Wählen", it: "Perché Sceglierci", ht: "Poukisa Chwazi Nou" },
  "whyus.title":      { en: "What Sets AMG Apart", es: "Lo Que Distingue a AMG", pt: "O Que Diferencia a AMG", fr: "Ce Qui Distingue AMG", de: "Was AMG Auszeichnet", it: "Cosa Distingue AMG", ht: "Sa Ki Diferansye AMG" },

  /* ── AREAS ── */
  "areas.eyebrow":    { en: "Service Area", es: "Área de Servicio", pt: "Área de Serviço", fr: "Zone de Service", de: "Servicegebiet", it: "Zona di Servizio", ht: "Zòn Sèvis" },
  "areas.title":      { en: "Serving All of Palm Beach County", es: "Sirviendo Todo el Condado de Palm Beach", pt: "Atendendo Todo o Condado de Palm Beach", fr: "Couvrant Tout le Comté de Palm Beach", de: "Wir bedienen ganz Palm Beach County", it: "Serviamo Tutto Palm Beach County", ht: "Sèvi Tout Palm Beach County" },
  "areas.lead":       { en: "From the coast to the western communities — if you're in Palm Beach County, we come to you.", es: "Desde la costa hasta las comunidades del oeste — si estás en el Condado de Palm Beach, vamos a ti.", pt: "Da costa às comunidades ocidentais — se você está no Condado de Palm Beach, nós vamos até você.", fr: "De la côte aux communautés de l'ouest — si vous êtes dans le comté de Palm Beach, nous venons chez vous.", de: "Von der Küste bis zu den westlichen Gemeinden — wenn Sie in Palm Beach County sind, kommen wir zu Ihnen.", it: "Dalla costa alle comunità occidentali — se sei a Palm Beach County, veniamo da te.", ht: "Depi kòt la rive nan kominote lwès yo — si ou nan Palm Beach County, nou vini jwenn ou." },

  /* ── REVIEWS ── */
  "reviews.eyebrow":  { en: "Customer Reviews", es: "Reseñas de Clientes", pt: "Avaliações de Clientes", fr: "Avis Clients", de: "Kundenbewertungen", it: "Recensioni dei Clienti", ht: "Revizyon Kliyan" },
  "reviews.title":    { en: "What Our Customers Say", es: "Lo Que Dicen Nuestros Clientes", pt: "O Que Nossos Clientes Dizem", fr: "Ce Que Disent Nos Clients", de: "Was Unsere Kunden Sagen", it: "Cosa Dicono i Nostri Clienti", ht: "Sa Kliyan Nou Di" },

  /* ── FAQ ── */
  "faq.eyebrow":      { en: "FAQ", es: "FAQ", pt: "FAQ", fr: "FAQ", de: "FAQ", it: "FAQ", ht: "FAQ" },
  "faq.title":        { en: "Frequently Asked Questions", es: "Preguntas Frecuentes", pt: "Perguntas Frequentes", fr: "Foire Aux Questions", de: "Häufig gestellte Fragen", it: "Domande Frequenti", ht: "Kesyon Yo Poze Souvan" },
  "faq.subtitle":     { en: "Have a question not listed here? Our team is always happy to help.", es: "¿Tienes una pregunta que no está aquí? Nuestro equipo siempre está listo para ayudar.", pt: "Tem uma pergunta que não está aqui? Nossa equipe está sempre pronta para ajudar.", fr: "Vous avez une question qui n'est pas listée ici ? Notre équipe est toujours prête à vous aider.", de: "Haben Sie eine Frage, die hier nicht aufgeführt ist? Unser Team hilft Ihnen gerne.", it: "Hai una domanda non elencata qui? Il nostro team è sempre felice di aiutare.", ht: "Ou gen yon kesyon ki pa la? Ekip nou an toujou pare pou ede." },
  "faq.contact":      { en: "Contact Form", es: "Formulario de Contacto", pt: "Formulário de Contato", fr: "Formulaire de Contact", de: "Kontaktformular", it: "Modulo di Contatto", ht: "Fòm Kontakt" },

  /* ── CONTACT ── */
  "contact.eyebrow":  { en: "Get In Touch", es: "Contáctenos", pt: "Entre em Contato", fr: "Contactez-nous", de: "Kontaktieren Sie uns", it: "Contattaci", ht: "Kontakte Nou" },
  "contact.title":    { en: "Get Your Free Quote", es: "Obtén Tu Presupuesto Gratis", pt: "Obtenha Seu Orçamento Grátis", fr: "Obtenez Votre Devis Gratuit", de: "Holen Sie sich Ihr kostenloses Angebot", it: "Ottieni il Tuo Preventivo Gratuito", ht: "Jwenn Estimasyon Gratis Ou" },
  "contact.name":     { en: "Your Name", es: "Tu Nombre", pt: "Seu Nome", fr: "Votre Nom", de: "Ihr Name", it: "Il Tuo Nome", ht: "Non Ou" },
  "contact.phone":    { en: "Phone Number", es: "Número de Teléfono", pt: "Número de Telefone", fr: "Numéro de Téléphone", de: "Telefonnummer", it: "Numero di Telefono", ht: "Nimewo Telefòn" },
  "contact.message":  { en: "Describe your job...", es: "Describe tu trabajo...", pt: "Descreva seu trabalho...", fr: "Décrivez votre besoin...", de: "Beschreiben Sie Ihren Auftrag...", it: "Descrivi il tuo lavoro...", ht: "Dekri travay ou..." },
  "contact.send":     { en: "Send via WhatsApp", es: "Enviar por WhatsApp", pt: "Enviar pelo WhatsApp", fr: "Envoyer par WhatsApp", de: "Per WhatsApp senden", it: "Invia via WhatsApp", ht: "Voye pa WhatsApp" },
  "contact.hours":    { en: "Mon–Sun 7 am–8 pm", es: "Lun–Dom 7 am–8 pm", pt: "Seg–Dom 7h–20h", fr: "Lun–Dim 7h–20h", de: "Mo–So 7–20 Uhr", it: "Lun–Dom 7–20", ht: "Lun–Dim 7 am–8 pm" },

  /* ── OFFER ── */
  "offer.title":      { en: "$20 OFF Your First Service", es: "$20 de Descuento en Tu Primer Servicio", pt: "$20 de Desconto no Seu Primeiro Serviço", fr: "$20 de Réduction sur Votre Premier Service", de: "$20 Rabatt auf Ihren ersten Service", it: "$20 di Sconto sul Tuo Primo Servizio", ht: "$20 Rabè sou Premye Sèvis Ou" },
  "offer.desc":       { en: "Mention this offer when you call or text.", es: "Menciona esta oferta cuando llames o escribas.", pt: "Mencione esta oferta quando ligar ou escrever.", fr: "Mentionnez cette offre en appelant ou en écrivant.", de: "Erwähnen Sie dieses Angebot beim Anrufen oder Schreiben.", it: "Menziona questa offerta quando chiami o scrivi.", ht: "Mansyone òf sa a lè ou rele oswa ekri." },
  "offer.cta":        { en: "Claim Offer", es: "Reclamar Oferta", pt: "Reivindicar Oferta", fr: "Réclamer l'Offre", de: "Angebot Beanspruchen", it: "Riscatta Offerta", ht: "Reklame Òf" },

  /* ── FOOTER ── */
  "footer.rights":    { en: "All rights reserved.", es: "Todos los derechos reservados.", pt: "Todos os direitos reservados.", fr: "Tous droits réservés.", de: "Alle Rechte vorbehalten.", it: "Tutti i diritti riservati.", ht: "Tout dwa rezève." },
};

export const SUPPORTED_LANGS: LangCode[] = ["en", "es", "pt", "fr", "de", "it", "ht"];

export function t(key: string, lang: LangCode): string {
  return translations[key]?.[lang] ?? translations[key]?.["en"] ?? key;
}
